import { calculateRecommendation } from "./routing";
import type { AppState, Encounter, Patient, DraftEncounter } from "./types";

const now = new Date("2026-08-30T09:00:00+05:30");

function iso(mins: number) {
  return new Date(now.getTime() + mins * 60000).toISOString();
}

function patient(id: string, name: string, age: number, sex: Patient["sex"], previousRecord: Patient["previousRecord"], previousSummary?: string): Patient {
  const ageGroup = age < 2 ? "Infant" : age < 13 ? "Child" : age >= 65 ? "Geriatric" : "Adult";
  return { id, name, age, ageGroup, sex, previousRecord, previousSummary, phone: `+91 9${Math.floor(100000000 + Math.random() * 899999999)}` };
}

const patients = [
  patient("P-1001", "Ramesh Kulkarni", 72, "Male", "Available", "Known hypertension; prior emergency visit for breathing concern."),
  patient("P-1002", "Anika Sharma", 4, "Female", "Not found"),
  patient("P-1003", "Meera Iyer", 31, "Female", "Available", "Pregnancy record available; 28 weeks noted in synthetic demo chart."),
  patient("P-1004", "Imran Khan", 45, "Male", "Unknown"),
  patient("P-1005", "Sunita Patil", 68, "Female", "Available", "Diabetes and hypertension listed in synthetic history."),
  patient("P-1006", "Aarav Deshmukh", 9, "Male", "Available", "Pediatric asthma note in synthetic record."),
  patient("P-1007", "Kavita Nair", 54, "Female", "Not found"),
  patient("P-1008", "Rahul Verma", 28, "Male", "Unknown"),
  patient("P-1009", "Fatima Ansari", 63, "Female", "Available", "Previous cardiac review pathway two years ago."),
  patient("P-1010", "Dev Malhotra", 19, "Male", "Not found"),
  patient("P-1011", "Bhavna Shah", 37, "Female", "Available", "Known allergy to penicillin."),
  patient("P-1012", "Nikhil Rao", 42, "Male", "Not found"),
  patient("P-1013", "Leela Menon", 76, "Female", "Available", "Prior stroke-like episode in synthetic record."),
  patient("P-1014", "Sana Qureshi", 24, "Female", "Unknown"),
  patient("P-1015", "Vikram Singh", 33, "Male", "Not found"),
  patient("P-1016", "Gauri Joshi", 58, "Female", "Available", "On regular medication for blood pressure."),
  patient("P-1017", "Om Prakash", 81, "Male", "Unknown"),
  patient("P-1018", "Tara Bhosale", 2, "Female", "Not found"),
  patient("P-1019", "Harsh Jain", 16, "Male", "Available", "Sports injury visit last year."),
  patient("P-1020", "Priya Reddy", 29, "Female", "Not found"),
];

const baseResources: AppState["resources"] = [
  { id: "R1", name: "ED bed", category: "Beds", total: 34, available: 8, status: "Available", location: "Emergency General" },
  { id: "R2", name: "Critical care bay", category: "Rooms", total: 4, available: 1, status: "Constrained", location: "Resuscitation" },
  { id: "R3", name: "Trauma bay", category: "Rooms", total: 5, available: 2, status: "Available", location: "Trauma" },
  { id: "R4", name: "Observation bed", category: "Beds", total: 18, available: 5, status: "Available", location: "Observation" },
  { id: "R5", name: "Pediatric bed", category: "Beds", total: 10, available: 2, status: "Constrained", location: "Pediatrics" },
  { id: "R6", name: "Isolation room", category: "Rooms", total: 6, available: 1, status: "Constrained", location: "Isolation" },
  { id: "R7", name: "ECG machine", category: "Equipment", total: 5, available: 2, status: "Available", location: "Emergency" },
  { id: "R8", name: "Monitor", category: "Equipment", total: 28, available: 7, status: "Available", location: "Emergency" },
  { id: "R9", name: "Oxygen point", category: "Equipment", total: 22, available: 6, status: "Available", location: "Emergency" },
  { id: "R10", name: "Imaging slot", category: "Equipment", total: 12, available: 3, status: "Constrained", location: "Radiology" },
  { id: "R11", name: "Emergency physician", category: "Staff", total: 8, available: 4, status: "Available", location: "ED" },
  { id: "R12", name: "Nurse review", category: "Staff", total: 22, available: 11, status: "Available", location: "ED" },
];

let tokenCounter = 84;
function encounter(partial: Partial<Encounter> & Pick<Encounter, "id" | "patientId" | "primaryConcern" | "symptoms" | "freeText">): Encounter {
  const tok = `C-0${tokenCounter++}`;
  const e: Encounter = {
    id: partial.id,
    patientId: partial.patientId,
    token: partial.token ?? tok,
    arrivalMode: partial.arrivalMode ?? "Walk-in",
    arrivalStatus: partial.arrivalStatus ?? "Waiting",
    speakerSource: partial.speakerSource ?? "Patient",
    language: partial.language ?? "English",
    communicationLimitations: partial.communicationLimitations ?? [],
    patientCategories: partial.patientCategories ?? [],
    primaryConcern: partial.primaryConcern,
    symptoms: partial.symptoms,
    freeText: partial.freeText,
    onset: partial.onset ?? "Not clear",
    duration: partial.duration ?? "Unknown",
    reportedSeverity: partial.reportedSeverity ?? 5,
    trend: partial.trend ?? "Unknown",
    riskAnswers: partial.riskAnswers ?? {},
    vitals: partial.vitals ?? { consciousness: "Not recorded", unavailableReason: "Vitals not available yet" },
    history: partial.history ?? {
      conditions: "Unknown",
      medications: "Unknown",
      allergies: "Not asked yet",
      previousEpisode: "Unknown",
      recentVisit: "Unknown",
    },
    observations: partial.observations ?? [],
    medicoLegal: partial.medicoLegal ?? false,
    transcript: partial.transcript,
    photoAttached: partial.photoAttached ?? false,
    status: partial.status ?? "Waiting",
    currentPathway: partial.currentPathway ?? "Unassigned",
    assignedQueue: partial.assignedQueue ?? "Intake queue",
    waitingMins: partial.waitingMins ?? 0,
    recommendation: partial.recommendation as Encounter["recommendation"],
    journey: partial.journey ?? [{ time: iso(-20), event: "Encounter opened", actor: "Triage Nurse NUR-1042" }],
    updatedAt: iso(0),
    attendingNurseId: "NUR-1042",
  };
  e.recommendation = calculateRecommendation(e, baseResources, { safetyBias: 78, waitingTimeWeight: 42, congestionWeight: 55, uncertaintyEscalation: 72 });
  e.currentPathway = e.recommendation.pathway;
  e.assignedQueue = e.recommendation.destination;
  return e;
}

export function createDemoState(): AppState {
  const encounters = [
    encounter({
      id: "E-2001",
      patientId: "P-1001",
      token: "C-084",
      arrivalMode: "Pre-arrival call",
      speakerSource: "Family",
      language: "Hinglish",
      patientCategories: ["Geriatric"],
      primaryConcern: "Breathing difficulty",
      symptoms: ["Breathing difficulty", "Chest discomfort", "Weakness / fainting"],
      freeText: "Mere father ko afternoon se saans lene mein takleef hai aur chest mein heaviness bol rahe hain.",
      onset: "This afternoon",
      duration: "4 hours",
      reportedSeverity: 8,
      trend: "Worsening",
      vitals: { spo2: 90, pulse: 112, bpSystolic: 154, bpDiastolic: 92, respiratoryRate: 28, painScore: 7, consciousness: "Alert" },
      waitingMins: 12,
    }),
    encounter({
      id: "E-2002",
      patientId: "P-1002",
      token: "C-085",
      arrivalMode: "Walk-in",
      speakerSource: "Patient",
      language: "English",
      patientCategories: ["Child"],
      primaryConcern: "Fever with lethargy",
      symptoms: ["Fever/infection symptoms", "Pediatric fever/crying/lethargy"],
      freeText: "Child has fever and is less responsive than usual.",
      onset: "Not clear",
      duration: "1 day",
      reportedSeverity: 7,
      trend: "Worsening",
      vitals: { temperature: 39.1, pulse: 138, respiratoryRate: 30, consciousness: "Confused" },
      waitingMins: 18,
    }),
    encounter({
      id: "E-2003",
      patientId: "P-1003",
      token: "C-086",
      arrivalMode: "Walk-in",
      speakerSource: "Patient",
      language: "English",
      patientCategories: ["Pregnant patient"],
      primaryConcern: "Pregnancy-related pain",
      symptoms: ["Pregnancy-related concern", "Abdominal pain"],
      freeText: "28 weeks pregnant, abdominal pain since morning. No direct diagnosis shown in prototype.",
      onset: "Not clear",
      duration: "Unknown",
      reportedSeverity: 6,
      trend: "Unknown",
      vitals: { pulse: 102, bpSystolic: 136, bpDiastolic: 86, painScore: 6, consciousness: "Alert" },
      waitingMins: 25,
    }),
    encounter({
      id: "E-2004",
      patientId: "P-1004",
      token: "C-087",
      arrivalMode: "Walk-in",
      speakerSource: "Patient",
      language: "English",
      communicationLimitations: ["Confused"],
      patientCategories: [],
      primaryConcern: "Ambiguous weakness",
      symptoms: ["Weakness/fainting"],
      freeText: "I feel strange and weak. Cannot explain clearly.",
      onset: "Not clear",
      duration: "Unknown",
      reportedSeverity: 5,
      trend: "Unknown",
      riskAnswers: { contradiction: "Yes" },
      vitals: { consciousness: "Not recorded", unavailableReason: "Vitals not available yet" },
      waitingMins: 37,
    }),
    encounter({
      id: "E-2005",
      patientId: "P-1005",
      token: "C-088",
      arrivalMode: "Walk-in",
      speakerSource: "Patient",
      language: "English",
      patientCategories: ["Geriatric"],
      primaryConcern: "Sudden confusion and weakness",
      symptoms: ["Confusion/altered behavior", "Stroke-like symptoms"],
      freeText: "Family reports sudden speech difficulty and arm weakness.",
      onset: "Not clear",
      duration: "Unknown",
      reportedSeverity: 8,
      trend: "Worsening",
      vitals: { pulse: 96, bpSystolic: 168, bpDiastolic: 94, consciousness: "Confused" },
      waitingMins: 9,
    }),
    encounter({
      id: "E-2006",
      patientId: "P-1008",
      token: "C-089",
      arrivalMode: "Ambulance",
      speakerSource: "Ambulance staff",
      language: "English",
      patientCategories: [],
      primaryConcern: "Road traffic accident",
      symptoms: ["Injury/trauma", "Bleeding"],
      freeText: "Bike accident, visible leg injury and bleeding.",
      onset: "Not clear",
      duration: "Unknown",
      medicoLegal: true,
      reportedSeverity: 7,
      vitals: { pulse: 122, bpSystolic: 100, bpDiastolic: 68, painScore: 9, consciousness: "Alert" },
      observations: ["Visible bleeding", "Mobility limitation"],
      waitingMins: 4,
    }),
    encounter({
      id: "E-2007",
      patientId: "P-1011",
      token: "C-090",
      arrivalMode: "Walk-in",
      speakerSource: "Patient",
      language: "English",
      patientCategories: [],
      primaryConcern: "Allergic reaction",
      symptoms: ["Allergic reaction", "Breathing difficulty"],
      freeText: "Swelling on lips with rash after food. Breathing feels tight.",
      onset: "Not clear",
      duration: "Unknown",
      reportedSeverity: 8,
      vitals: { pulse: 118, spo2: 93, respiratoryRate: 26, consciousness: "Alert" },
      waitingMins: 5,
    }),
    encounter({
      id: "E-2008",
      patientId: "P-1019",
      token: "C-091",
      arrivalMode: "Walk-in",
      speakerSource: "Patient",
      language: "English",
      patientCategories: [],
      primaryConcern: "Minor sports injury",
      symptoms: ["Injury/trauma"],
      freeText: "Minor ankle sprain after football. Walking with support.",
      onset: "Not clear",
      duration: "Unknown",
      reportedSeverity: 3,
      vitals: { pulse: 84, bpSystolic: 116, bpDiastolic: 76, painScore: 4, consciousness: "Alert" },
      waitingMins: 44,
    }),
    encounter({
      id: "E-2009",
      patientId: "P-1017",
      token: "C-092",
      arrivalMode: "Walk-in",
      speakerSource: "Patient",
      language: "Hindi",
      communicationLimitations: [],
      patientCategories: ["Geriatric", "Communication-impaired"],
      primaryConcern: "Fever and cough",
      symptoms: ["Fever/infection symptoms", "Breathing difficulty"],
      freeText: "Bukhar, khansi, aur saans phool rahi hai. History unclear.",
      reportedSeverity: 6,
      vitals: { temperature: 38.8, spo2: 91, pulse: 106, respiratoryRate: 25, consciousness: "Confused" },
      waitingMins: 31,
    }),
    encounter({
      id: "E-2010",
      patientId: "P-1018",
      token: "C-093",
      arrivalMode: "Walk-in",
      speakerSource: "Family",
      language: "Marathi",
      primaryConcern: "Infant crying and fever",
      symptoms: ["Pediatric fever/crying/lethargy", "Fever/infection symptoms"],
      freeText: "Baalak satat radat aahe, dudh kami ghet aahe, tap aahe.",
      reportedSeverity: 7,
      vitals: { temperature: 38.9, pulse: 150, consciousness: "Alert" },
      waitingMins: 14,
    }),
  ];

  const drafts: DraftEncounter[] = [
    {
      id: "DRAFT-101",
      patientName: "Amit Sharma",
      age: 65,
      startedAt: iso(-18),
      completionPct: 65,
      currentStage: 6,
      data: {
        arrivalMode: "Walk-in",
        speakerSource: "Family",
        language: "Hinglish",
        patientCategories: ["Geriatric"],
        primaryConcern: "Chest discomfort",
        symptoms: ["Chest discomfort", "Weakness / fainting"],
        freeText: "Ch छाती में दर्द हो रहा है सुबह से.",
        vitals: { pulse: 98, bpSystolic: 145, bpDiastolic: 88, spo2Unavailable: true, consciousness: "Not recorded" }
      }
    },
    {
      id: "DRAFT-102",
      patientName: "Karan Johar",
      age: 38,
      startedAt: iso(-45),
      completionPct: 40,
      currentStage: 4,
      data: {
        arrivalMode: "Pre-arrival call",
        speakerSource: "Patient",
        language: "English",
        primaryConcern: "Abdominal pain",
        symptoms: ["Abdominal pain"],
        freeText: "Severe abdominal cramps after dinner."
      }
    }
  ];

  return {
    hospital: {
      id: "H-CITYCARE",
      name: "CityCare Hospital",
      location: "Mid-sized Indian City",
      jurisdiction: "India - DPDP Act plus hospital privacy and security policy",
      normalDailyVolume: 250,
      currentMode: "Normal",
      syntheticDataNotice: "All patients, staff, records, thresholds, and transcripts are synthetic demo data. Clinical thresholds require validation.",
    },
    nurseSession: {
      rollNumber: "NUR-1042",
      name: "Nurse Neha Kapoor",
      hospitalName: "CityCare Hospital",
      department: "Emergency Department",
      loggedInAt: iso(-120)
    },
    drafts,
    departments: [
      { id: "D1", name: "Emergency General", type: "Queue", capacity: 34, currentLoad: 24, staffAvailable: 11, averageServiceMins: 42 },
      { id: "D2", name: "Resuscitation / Critical Care Bay", type: "Escalation", capacity: 4, currentLoad: 3, staffAvailable: 4, averageServiceMins: 18 },
      { id: "D3", name: "Trauma", type: "Queue", capacity: 5, currentLoad: 3, staffAvailable: 5, averageServiceMins: 35 },
      { id: "D4", name: "Cardiac Review", type: "Queue", capacity: 6, currentLoad: 4, staffAvailable: 3, averageServiceMins: 28 },
      { id: "D5", name: "Stroke / Neuro Review", type: "Queue", capacity: 4, currentLoad: 2, staffAvailable: 2, averageServiceMins: 31 },
      { id: "D6", name: "Pediatrics", type: "Queue", capacity: 10, currentLoad: 8, staffAvailable: 4, averageServiceMins: 38 },
      { id: "D7", name: "Obstetrics", type: "Queue", capacity: 6, currentLoad: 3, staffAvailable: 3, averageServiceMins: 40 },
      { id: "D8", name: "Fast Track / Minor Care", type: "Queue", capacity: 12, currentLoad: 9, staffAvailable: 3, averageServiceMins: 22 },
      { id: "D9", name: "Observation", type: "Queue", capacity: 18, currentLoad: 13, staffAvailable: 5, averageServiceMins: 90 },
      { id: "D10", name: "Imaging", type: "Support", capacity: 12, currentLoad: 9, staffAvailable: 4, averageServiceMins: 25 },
      { id: "D11", name: "Isolation / Infection Concern", type: "Queue", capacity: 6, currentLoad: 5, staffAvailable: 3, averageServiceMins: 45 },
      { id: "D12", name: "ICU Escalation", type: "Escalation", capacity: 8, currentLoad: 7, staffAvailable: 6, averageServiceMins: 120 },
    ],
    resources: baseResources,
    staff: [
      { id: "S1", name: "Dr. Ananya Rao", role: "Emergency Physician", department: "Emergency General", status: "Available" },
      { id: "S2", name: "Dr. Kabir Mehta", role: "Cardiac Review Lead", department: "Cardiac Review", status: "Busy" },
      { id: "S3", name: "Dr. Farah Siddiqui", role: "Pediatrician", department: "Pediatrics", status: "Available" },
      { id: "S4", name: "Nurse Neha Kapoor", role: "Triage Nurse", department: "Nurse Tablet", status: "Available" },
      { id: "S5", name: "Nurse Ajay More", role: "Trauma Nurse", department: "Trauma", status: "Available" },
      { id: "S6", name: "Dr. Shalini Menon", role: "OB Consultant", department: "Obstetrics", status: "Available" },
    ],
    patients,
    encounters,
    alerts: [
      { id: "A1", encounterId: "E-2004", level: "Warning", title: "Ambiguous intake", detail: "Weakness case has missing vitals and contradictory history.", createdAt: iso(-8), acknowledged: false },
      { id: "A2", encounterId: "E-2005", level: "Critical", title: "Waiting patient needs review", detail: "Sudden neuro review signals with worsening trend.", createdAt: iso(-4), acknowledged: false },
      { id: "A3", level: "Warning", title: "Pediatric beds constrained", detail: "Pediatric pathway has limited available beds.", createdAt: iso(-2), acknowledged: false },
    ],
    audit: [
      { id: "AU1", actor: "System", action: "DEMO_RESET", target: "CityCare", detail: "Seeded CityCare Hospital with synthetic data.", createdAt: iso(-60) },
      { id: "AU2", actor: "Nurse NUR-1042", action: "RECOMMENDATION_OVERRIDDEN", target: "E-2008", detail: "Moved minor sports injury to Fast Track after nurse review.", createdAt: iso(-14) },
      { id: "AU3", actor: "System", action: "REASSESSMENT_ALERT", target: "E-2005", detail: "Generated reassessment alert for worsening waiting patient.", createdAt: iso(-4) },
    ],
    routingPolicy: { safetyBias: 78, waitingTimeWeight: 42, congestionWeight: 55, uncertaintyEscalation: 72 },
    simulation: {
      baselineMedianWait: 58,
      dynamicMedianWait: 36,
      baselineHighRiskDelay: 22,
      dynamicHighRiskDelay: 8,
      overtriagePressure: 64,
      reassessmentsToday: 7,
    },
  };
}
