/** @type {import('tailwindcss').Config} */
// Design tokens copied verbatim from stitch_patienttriage.ai_nurse_portal/*/code.html
// (identical tailwind.config block embedded in every generated screen).
module.exports = {
  content: ["./App.tsx", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        tertiary: "#7e3000",
        "on-tertiary-container": "#ffd2be",
        "secondary-fixed-dim": "#bec6e0",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4d44e3",
        "primary-container": "#4f46e5",
        "on-secondary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-container-highest": "#e4e1ee",
        "inverse-primary": "#c3c0ff",
        outline: "#777587",
        "tertiary-fixed": "#ffdbcc",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-fixed-dim": "#ffb695",
        "primary-fixed": "#e2dfff",
        "surface-dim": "#dcd8e5",
        "surface-container": "#f0ecf9",
        "on-primary-container": "#dad7ff",
        "on-surface-variant": "#464555",
        "surface-container-high": "#eae6f4",
        "surface-bright": "#fcf8ff",
        "on-tertiary-fixed": "#351000",
        "on-surface": "#1b1b24",
        "secondary-fixed": "#dae2fd",
        "tertiary-container": "#a44100",
        "on-error": "#ffffff",
        primary: "#3525cd",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-container": "#5c647a",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-primary-fixed": "#0f0069",
        "outline-variant": "#c7c4d8",
        secondary: "#565e74",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f3effc",
        background: "#fcf8ff",
        "on-primary": "#ffffff",
        "inverse-surface": "#302f39",
        "on-background": "#1b1b24",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e4e1ee",
        "surface-container-low": "#f5f2ff",
        surface: "#fcf8ff",
        // Triage urgency semantics (traffic-light system, DESIGN.md)
        "urgency-1": "#ba1a1a",
        "urgency-2": "#c2410c",
        "urgency-3": "#b45309",
        "urgency-4": "#2563eb",
        "urgency-5": "#16a34a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "24px",
        "stack-gap": "12px",
        unit: "4px",
        "touch-target-min": "44px",
        "container-padding": "16px",
      },
      fontFamily: {
        "body-lg": ["Inter_400Regular"],
        "headline-lg": ["Inter_700Bold"],
        "body-md": ["Inter_400Regular"],
        "label-caps": ["Inter_600SemiBold"],
        "headline-md": ["Inter_600SemiBold"],
        "helper-text": ["Inter_400Regular"],
        "stat-value": ["Inter_700Bold"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "helper-text": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "stat-value": ["24px", { lineHeight: "30px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
